"""Anadir tabla EncuestaAsignada y relaciones para envio de encuestas

Revision ID: d9083a8d3b72
Revises: d99f38b792b2
Create Date: 2025-10-27 23:35:54.302153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9083a8d3b72'
down_revision = 'd99f38b792b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encuesta_asignada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_encuesta', sa.Integer(), nullable=False),
    sa.Column('id_egresado', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('respondida', sa.Boolean(), nullable=False),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_egresado'], ['egresado.id'], ),
    sa.ForeignKeyConstraint(['id_encuesta'], ['encuesta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encuesta_asignada')
    # ### end Alembic commands ###
