"""Anadir campo foto_perfil a Personal y Autoridad

Revision ID: d99f38b792b2
Revises: ed9f392e80b6
Create Date: 2025-10-27 22:36:05.708734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99f38b792b2'
down_revision = 'ed9f392e80b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autoridad_universitaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil_filename', sa.String(length=100), nullable=True))

    with op.batch_alter_table('personal_seguimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil_filename', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_seguimiento', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil_filename')

    with op.batch_alter_table('autoridad_universitaria', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil_filename')

    # ### end Alembic commands ###
