"""Anadir campo foto_perfil a Egresado

Revision ID: ed9f392e80b6
Revises: 
Create Date: 2025-10-27 20:26:07.270784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9f392e80b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('egresado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil_filename', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('egresado', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil_filename')

    # ### end Alembic commands ###
